[build]
builder = "NIXPACKS"
buildCommand = "go build -o bin/api src/main.go"

[deploy]
startCommand = "./bin/api"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"
